import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE);const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema account_private;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create table auth.users(id uuid primary key);
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade);
create table public.universities(id uuid primary key,name text not null,is_active boolean not null default true);
create table public.account_deletion_requests(subject_id uuid,state text);`);
const lifecycle=readFileSync('supabase/migrations/20261001000300_account_deletion_lifecycle.sql','utf8');
await db.exec(lifecycle.slice(lifecycle.indexOf('create function account_private.lock_subject'),lifecycle.indexOf('create function account_private.guard_request')));
await db.exec(readFileSync('supabase/migrations/20261008000600_student_application_foundation.sql','utf8'));
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',u='00000000-0000-4000-8000-000000000003';
let key=10;const uuid=()=>`00000000-0000-4000-8000-${String(++key).padStart(12,'0')}`;
await db.exec(`insert into auth.users values('${a}'),('${b}');insert into profiles select id from auth.users;insert into universities(id,name) values('${u}','연세대학교');`);
const session=async(role,owner='')=>db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${owner}',false);`);
const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
const save=(id=null,revision=0,division='경영학과',request=uuid())=>scalar('select my_application_save($1,$2,2027,$3,$4,\'수시\',\'논술전형\',$5)',[id,revision,u,division,request]);
const event=(id,kind='submitted',supersedes=null,request=uuid())=>scalar('select my_application_event($1,$2,\'2026-10-08T00:00:00Z\',$3,$4)',[id,kind,supersedes,request]);
await session('anon');await assert.rejects(scalar('select my_applications()'),e=>e.code==='42501');
await session('authenticated',a);
const request=uuid(),id=await save(null,0,'경영학과',request);
assert.equal(await save(null,0,'경영학과',request),id);
await assert.rejects(save(null,0,'경제학부',request),e=>e.code==='23514');
await assert.rejects(db.query('update student_applications set intended_division=\'위조\''),e=>e.code==='42501');
assert.equal((await scalar('select my_applications()')).items[0].intended_division,'경영학과');
await save(id,1,'경제학부');await assert.rejects(save(id,1,'경영학과'),e=>e.code==='40001');
const first=await event(id),second=await event(id,'accepted');
const correctionKey=uuid(),correction=await event(id,'rejected',second,correctionKey);
assert.equal(await event(id,'rejected',second,correctionKey),correction);
await assert.rejects(event(id,'accepted',second),e=>e.code==='23514');
let history=(await scalar('select my_application_events($1)',[id])).items;
assert.equal(history.length,5);assert.equal(history.find(e=>e.id===correction).supersedes_event_id,second);
assert.equal(history.find(e=>e.kind==='details_changed').payload.before.intended_division,'경영학과');
assert.equal((await scalar('select my_applications()')).items[0].latest_event.kind,'rejected');
await session('authenticated',b);
assert.equal((await scalar('select my_applications()')).items.length,0);
assert.equal(await scalar('select count(*)::int from student_applications'),0);
await assert.rejects(save(id,2),e=>e.code==='42501');await assert.rejects(event(id),e=>e.code==='42501');
await assert.rejects(scalar('select my_application_events($1)',[id]),e=>e.code==='42501');
await assert.rejects(scalar('select my_application_delete($1)',[id]),e=>e.code==='42501');
const own=await save();await scalar('select my_application_delete($1)',[own]);assert.equal((await scalar('select my_applications()')).items.length,0);
await db.exec(`reset role;insert into account_deletion_requests values('${a}','DELETION_PENDING');`);
await session('authenticated',a);await assert.rejects(save(),e=>e.code==='42501');await assert.rejects(scalar('select my_applications()'),e=>e.code==='42501');assert.equal(await scalar('select count(*)::int from student_application_events'),0);
await db.exec(`reset role;delete from auth.users where id='${a}';`);
assert.equal(await scalar('select count(*)::int from student_applications'),0);assert.equal(await scalar('select count(*)::int from student_application_events'),0);
assert.ok(first);console.log('APPLICATION_SQL PASS: anonymous/direct writes/other owner/lifecycle denied; revision, idempotency, history, corrections, explicit delete and Auth cascade verified');await db.close();
