import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE);const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema account_private;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key);
create table profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,academic_status text,neis_office_code text,neis_school_code text,grade_level smallint,intended_major text);
create table universities(id uuid primary key,name text,is_active boolean default true);
create table admin_users(user_id uuid primary key);create table quality_operators(user_id uuid primary key);
create table account_deletion_requests(subject_id uuid,state text);
-- Read-model fixture columns follow canonical 20260928000100; these are not security mocks.
create table essay_exams(id uuid primary key,admission_year integer,university_id uuid);
create table essay_questions(id uuid primary key,essay_exam_id uuid,label text);
create table essay_practice_sessions(id uuid primary key,question_id uuid,user_id uuid,created_at timestamptz);
create table essay_attempts(id uuid primary key,session_id uuid,submitted_at timestamptz,question_metadata_version text,body text);
create table essay_evaluations(id uuid primary key,attempt_id uuid,question_id uuid,session_id uuid,status text,request_kind text,invalidated_at timestamptz,completed_at timestamptz,supersedes_evaluation_id uuid,regime_key text,evaluation_version text,contract_version text,evidence_manifest_sha256 text,requested_at timestamptz,strengths text[],rewrite_checklist text[]);
create table essay_evaluation_criteria(id uuid primary key,definition_version text);
create table essay_evaluation_dimensions(evaluation_id uuid,criterion_id uuid,level_1_to_5 integer,display_order integer);`);
const lifecycle=readFileSync('supabase/migrations/20261001000300_account_deletion_lifecycle.sql','utf8');
await db.exec(lifecycle.slice(lifecycle.indexOf('create function account_private.lock_subject'),lifecycle.indexOf('create function account_private.guard_request')));
await db.exec(readFileSync('supabase/verification/my_foundation/fixtures/admin_operator.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20260914000100_study_sessions.sql','utf8'));
await db.exec('alter table study_sessions add column include_in_study_total boolean not null default true;');
for(const name of ['20261008000600_student_application_foundation','20261008000700_shared_study_summary','20261008000800_student360_read_foundation'])await db.exec(readFileSync(`supabase/migrations/${name}.sql`,'utf8'));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const [a,b,admin,quality]=[1,2,3,4].map(id);
await db.exec(`insert into auth.users values('${a}'),('${b}'),('${admin}'),('${quality}');insert into profiles(id,academic_status,neis_office_code,neis_school_code) values('${a}','student','B10','123');insert into admin_users values('${admin}');insert into quality_operators values('${quality}');
insert into universities(id,name) values('${id(5)}','테스트대학교');insert into essay_exams values('${id(6)}',2027,'${id(5)}');insert into essay_questions values('${id(7)}','${id(6)}','문제 1');insert into essay_practice_sessions values('${id(8)}','${id(7)}','${a}',now());insert into essay_attempts values('${id(9)}','${id(8)}',now(),'v1','DO_NOT_RETURN_ANSWER');`);
const session=async(role,owner,expired=false)=>{await db.exec(`reset role;set role ${role}`);await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[owner??'',JSON.stringify({sub:owner,role,exp:expired?1:9999999999})]);};
const read=async()=> (await db.query('select admin_student360($1) value',[a])).rows[0].value;
await session('anon');await assert.rejects(read(),e=>e.code==='42501');
await session('authenticated',a);await assert.rejects(read(),e=>e.code==='42501');
await session('authenticated',quality);await assert.rejects(read(),e=>e.code==='42501');
await session('authenticated',admin,true);await assert.rejects(read(),e=>e.code==='42501');
await session('authenticated',admin);const s=await read();assert.equal(s.identity.academic_status,'student');assert.equal(s.study.last30_ms,0);assert.equal(s.applications.items.length,0);assert.equal(s.essay.sessions[0].attempt_count,1);assert.equal(s.essay.sessions[0].university_name,'테스트대학교');assert.equal(s.academic_performance,null);assert.equal(s.period_entitlement,null);assert.ok(!JSON.stringify(s).includes('DO_NOT_RETURN_ANSWER'));
await session('authenticated',b);assert.equal((await db.query('select my_essay_summary() value')).rows[0].value.sessions.length,0);
await session('authenticated',a);assert.equal((await db.query('select my_essay_summary() value')).rows[0].value.sessions.length,1);
await db.exec(`reset role;insert into account_deletion_requests values('${a}','ERASING');`);await session('authenticated',admin);await assert.rejects(read(),e=>e.code==='42501');
console.log('STUDENT360_SQL PASS: admin allow; anonymous/normal/quality-only/expired operator/erasing subject deny; self Essay isolation; school identity; bounded summary; no answer body');await db.close();
