import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE);
const db=new PGlite();const base=readFileSync('supabase/migrations/20260928000100_student_essay_product.sql','utf8');
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create table public.profiles(id uuid primary key);create table public.universities(id uuid primary key);
${base.slice(base.indexOf('create table public.student_target_universities ('),base.indexOf('create table public.essay_practice_sessions ('))}
${base.slice(base.indexOf('alter table public.student_target_universities enable'),base.indexOf('alter table public.essay_practice_sessions enable'))}`);
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',u='00000000-0000-4000-8000-000000000003';
await db.exec(`insert into profiles values('${a}'),('${b}');insert into universities values('${u}');insert into student_target_universities(user_id,university_id,status,source) values('${a}','${u}','interested','my');`);
const before=(await db.query('select * from student_target_universities')).rows;
await db.exec(readFileSync('supabase/migrations/20261008000500_target_division_identity.sql','utf8'));
assert.deepEqual((await db.query('select * from student_target_universities')).rows,before);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`);
const insert=async(d,year=null,owner=a)=>db.query('insert into student_target_universities(user_id,university_id,intended_division,admission_year,status,source) values($1,$2,$3,$4,\'interested\',\'my\')',[owner,u,d,year]);
await insert('경영학과');await insert('경제학부');await insert('경영학과',2027);
await assert.rejects(insert(' 경영학과 '),e=>e.code==='23505');await assert.rejects(insert('',null),e=>e.code==='23505');
await assert.rejects(insert('사칭',2027,b),e=>e.code==='42501');
assert.equal((await db.query('select count(*)::int n from student_target_universities')).rows[0].n,4);
await db.exec(`select set_config('request.jwt.claim.sub','${b}',false);`);
assert.equal((await db.query('select count(*)::int n from student_target_universities')).rows[0].n,0);
await insert('경영학과',null,b);
await db.exec('reset role');
await db.query('delete from profiles where id=$1',[b]);
assert.equal((await db.query('select count(*)::int n from student_target_universities where user_id=$1',[b])).rows[0].n,0);
console.log('TARGET_SQL: legacy rows preserved; same university different division/year allowed; normalized duplicates and cross-owner insert denied; owner reads isolated; profile deletion cascades PASS');
await db.close();
