// GENERATED by UNIVERSITY-BRAND-ASSETS-1 — do not edit by hand.
// Source: assets/universities/manifest.json (Release Core 50 brand assets).
//
// The key is public.universities.slug, which is the canonical identity used by
// the onboarding and My Page 관심 대학 pickers. A slug with no entry here must
// fall back to the neutral initial avatar — never to another university's mark.

/// Maps a `universities.slug` to a bundled brand asset path.
///
/// These marks identify the university the user picked. They do not imply any
/// partnership, sponsorship or endorsement by the university.
const Map<String, String> kUniversityLogoAssets = <String, String>{
  "gachon": "assets/universities/gachon.png",
  "catholic": "assets/universities/catholic.png",
  "kangwon": "assets/universities/kangwon.png",
  "konkuk": "assets/universities/konkuk.png",
  "kyonggi": "assets/universities/kyonggi.png",
  "kyungpook": "assets/universities/kyungpook.png",
  "gnu": "assets/universities/gnu.png",
  "kyunghee": "assets/universities/kyunghee.png",
  "keimyung": "assets/universities/keimyung.png",
  "korea": "assets/universities/korea.png",
  "kwangwoon": "assets/universities/kwangwoon.png",
  "gist": "assets/universities/gist.png",
  "kookmin": "assets/universities/kookmin.png",
  "dankook": "assets/universities/dankook.png",
  "dgist": "assets/universities/dgist.png",
  "dongguk": "assets/universities/dongguk.png",
  "donga": "assets/universities/donga.png",
  "myongji": "assets/universities/myongji.png",
  "pknu": "assets/universities/pknu.png",
  "pusan": "assets/universities/pusan.png",
  "sogang": "assets/universities/sogang.png",
  "seoultech": "assets/universities/seoultech.png",
  "seoul-national": "assets/universities/seoul-national.png",
  "uos": "assets/universities/uos.png",
  "sungkyunkwan": "assets/universities/sungkyunkwan.png",
  "sejong": "assets/universities/sejong.png",
  "sookmyung": "assets/universities/sookmyung.png",
  "soongsil": "assets/universities/soongsil.png",
  "ajou": "assets/universities/ajou.png",
  "yonsei": "assets/universities/yonsei.png",
  "yeungnam": "assets/universities/yeungnam.png",
  "unist": "assets/universities/unist.png",
  "ulsan": "assets/universities/ulsan.png",
  "ewha": "assets/universities/ewha.png",
  "incheon": "assets/universities/incheon.png",
  "inha": "assets/universities/inha.png",
  "chonnam": "assets/universities/chonnam.png",
  "jeonbuk": "assets/universities/jeonbuk.png",
  "jeju": "assets/universities/jeju.png",
  "chosun": "assets/universities/chosun.png",
  "chungang": "assets/universities/chungang.png",
  "chungnam": "assets/universities/chungnam.png",
  "chungbuk": "assets/universities/chungbuk.png",
  "postech": "assets/universities/postech.png",
  "kaist": "assets/universities/kaist.png",
  "hufs": "assets/universities/hufs.png",
  "hallym": "assets/universities/hallym.png",
  "hongik": "assets/universities/hongik.png",
};

/// Slugs that deliberately have no asset; render the neutral fallback.
const Set<String> kUniversityLogoFallbacks = <String>{
  "soonchunhyang",
  "hanyang",
};
