begin read only;
set local statement_timeout='30s';
set local search_path = pg_catalog, public;
select jsonb_build_object(
 'tables',(select coalesce(jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,
 'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'generated',a.attgenerated,'identity',a.attidentity,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
 'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid),'validated',convalidated) order by conname),'[]') from pg_constraint where conrelid=c.oid),
 'indexes',(select coalesce(jsonb_agg(jsonb_build_object('name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid) order by ic.relname),'[]') from pg_index i join pg_class ic on ic.oid=i.indexrelid where i.indrelid=c.oid),
 'policies',(select coalesce(jsonb_agg(jsonb_build_object('name',policyname,'roles',roles,'cmd',cmd,'permissive',permissive,'using',qual,'check',with_check) order by policyname),'[]') from pg_policies where schemaname=n.nspname and tablename=c.relname),
 'triggers',(select coalesce(jsonb_agg(jsonb_build_object('name',tgname,'definition',pg_get_triggerdef(oid),'enabled',tgenabled) order by tgname),'[]') from pg_trigger where tgrelid=c.oid and not tgisinternal),
 'table_acl',(select coalesce(jsonb_agg(jsonb_build_object('role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable) order by x.grantee,x.privilege_type),'[]') from aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x where x.grantee<>c.relowner),
 'column_acl',(select coalesce(jsonb_agg(jsonb_build_object('column',a.attname,'role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable) order by a.attname,x.grantee,x.privilege_type),'[]') from pg_attribute a cross join lateral aclexplode(a.attacl) x where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped and x.grantee<>c.relowner)
 ) order by n.nspname,c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','essay_private') and c.relkind in ('r','p','v','m')),
 'functions',(select coalesce(jsonb_agg(jsonb_build_object('name',n.nspname||'.'||p.proname,'args',pg_get_function_identity_arguments(p.oid),'args_with_defaults',pg_get_function_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',l.lanname,'definer',p.prosecdef,'volatility',p.provolatile,'strict',p.proisstrict,'config',p.proconfig,'owner',pg_get_userbyid(p.proowner),'definition',pg_get_functiondef(p.oid),'body_md5',md5(btrim(p.prosrc,E' \t\n\r')),'acl',(select jsonb_agg(jsonb_build_object('role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable)) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x where x.grantee<>p.proowner)) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname in ('public','essay_private') and p.prokind='f'),
 'read_only',current_setting('transaction_read_only'),'captured_at',now(),
 'migration_history',(select jsonb_agg(jsonb_build_object('version',version,'name',name,'statement_count',cardinality(statements),'statements_md5',md5(statements::text)) order by version) from supabase_migrations.schema_migrations),
 'avatar_bucket',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types)),'[]') from storage.buckets where id='profile-avatars'),
 'history_present',to_regclass('supabase_migrations.schema_migrations') is not null
) as catalog;
rollback;
