begin read only;
set local search_path = pg_catalog, public;
select jsonb_build_object(
 'tables',(select coalesce(jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,
 'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'generated',a.attgenerated,'identity',a.attidentity,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
 'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid),'validated',convalidated) order by conname),'[]') from pg_constraint where conrelid=c.oid),
 'indexes',(select coalesce(jsonb_agg(jsonb_build_object('name',ic.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid) order by ic.relname),'[]') from pg_index i join pg_class ic on ic.oid=i.indexrelid where i.indrelid=c.oid),
 'policies',(select coalesce(jsonb_agg(jsonb_build_object('name',policyname,'roles',roles,'cmd',cmd,'permissive',permissive,'using',qual,'check',with_check) order by policyname),'[]') from pg_policies where schemaname=n.nspname and tablename=c.relname),
 'triggers',(select coalesce(jsonb_agg(jsonb_build_object('name',tgname,'definition',pg_get_triggerdef(oid),'enabled',tgenabled) order by tgname),'[]') from pg_trigger where tgrelid=c.oid and not tgisinternal),
 'table_acl',(select coalesce(jsonb_agg(jsonb_build_object('role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable) order by x.grantee,x.privilege_type),'[]') from aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x where x.grantee<>c.relowner),
 'column_acl',(select coalesce(jsonb_agg(jsonb_build_object('column',a.attname,'role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable) order by a.attname,x.grantee,x.privilege_type),'[]') from pg_attribute a cross join lateral aclexplode(a.attacl) x where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped and x.grantee<>c.relowner)
 ) order by n.nspname,c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname||'.'||c.relname=any(array['public.admin_users','public.answer_key_versions','public.bookmarks','public.content_items','public.credit_accounts','public.credit_grants','public.credit_transactions','public.day_targets','public.essay_ai_processing_runs','public.essay_attempts','public.essay_billing_decisions','public.essay_drafts','public.essay_evaluation_criteria','public.essay_evaluation_dimensions','public.essay_evaluation_evidence','public.essay_evaluations','public.essay_exam_resources','public.essay_exams','public.essay_generated_rewrites','public.essay_improvement_items','public.essay_improvement_progress','public.essay_learning_events','public.essay_practice_sessions','public.essay_question_evidence','public.essay_questions','public.exam_questions','public.exam_subjects','public.exams','public.feedback_notifications','public.feedback_submissions','public.grade_cutoff_versions','public.ingestion_quarantine','public.mock_exam_answers','public.mock_exam_attempts','public.mock_exam_scoring_availability','public.profiles','public.recent_views','public.resource_resolver_quota','public.resources','public.source_posts','public.student_target_universities','public.study_sessions','public.subjects','public.universities','storage.buckets','storage.objects'])),
 'functions',(select coalesce(jsonb_agg(jsonb_build_object('name',n.nspname||'.'||p.proname,'args',pg_get_function_identity_arguments(p.oid),'args_with_defaults',pg_get_function_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',l.lanname,'definer',p.prosecdef,'volatility',p.provolatile,'strict',p.proisstrict,'config',p.proconfig,'owner',pg_get_userbyid(p.proowner),'body_md5',md5(btrim(p.prosrc,E' \t\n\r')),'acl',(select jsonb_agg(jsonb_build_object('role',case when x.grantee=0 then 'PUBLIC' else pg_get_userbyid(x.grantee) end,'privilege',x.privilege_type,'grantable',x.is_grantable)) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x where x.grantee<>p.proowner)) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname||'.'||p.proname=any(array['essay_private.clock','essay_private.fence','essay_private.hash','essay_private.lock_job','essay_private.owner','essay_private.release','essay_private.uid','public.claim_feedback_notifications','public.complete_feedback_notification','public.consume_resource_resolver_quota','public.enqueue_feedback_notification','public.essay_billing_history_guard','public.essay_claim','public.essay_credit_account_guard','public.essay_erase','public.essay_finalize_failure','public.essay_finalize_success','public.essay_open_session','public.essay_product_child_guard','public.essay_product_draft_guard','public.essay_product_processing_guard','public.essay_product_progress_guard','public.essay_product_reject_update','public.essay_product_terminal_guard','public.essay_question_identity_guard','public.essay_reconcile','public.essay_refund','public.essay_request_evaluation','public.essay_request_rewrite','public.essay_save_draft','public.essay_submit_attempt','public.essay_timeout','public.fail_feedback_notification','public.feedback_updated_at','public.fetch_own_mock_attempt','public.is_feedback_admin','public.reclaim_feedback_notification_leases','public.scoring_answer_guard','public.scoring_attempt_consistency','public.scoring_attempt_guard','public.scoring_cutoffs_valid','public.scoring_mcq5','public.scoring_normalize_answers','public.scoring_publication_guard','public.scoring_question_guard','public.scoring_source_url','public.scoring_text','public.set_updated_at','public.set_viewed_at','public.study_active_milliseconds','public.submit_mock_attempt'])),
 'avatar_bucket',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types)),'[]') from storage.buckets where id='profile-avatars'),
 'history_present',to_regclass('supabase_migrations.schema_migrations') is not null
) as catalog;
rollback;
