-- LegendStudy subjects taxonomy seed. NOT APPLIED.
-- Generated by tool/ingest_legendstudy.py --emit-subjects-seed.
-- Owner applies this; see wiki/day-9-subjects-taxonomy.md.
-- Deterministic ids: uuid5(uuid5(URL, "https://legendstudy.com/taxonomy"),
--                         "<taxonomy_version>:<code>").
-- Rerunning is a no-op: ON CONFLICT DO NOTHING never edits a released row.
begin;

insert into public.subjects
    (id, code, name, category, taxonomy_version, curriculum_version,
     parent_id, is_active, sort_order)
values
    ('9ae14424-dad0-593c-bf7e-96dca10e719f', 'korean', '국어', '공통', 'v1', null, null, true, 10),
    ('00c4dde1-7015-5656-8c84-443a30e9e472', 'math', '수학', '공통', 'v1', null, null, true, 20),
    ('5e92466e-acbb-5bdb-8c5a-b300e28aaf28', 'english', '영어', '공통', 'v1', null, null, true, 30),
    ('8bc327fb-e433-5e39-94dd-7f22060518f9', 'korean_history', '한국사', '공통', 'v1', null, null, true, 40),
    ('9258263d-e6ec-5e6a-a6bb-d71fc4d2b3e8', 'integrated_social', '통합사회', '통합', 'v1', null, null, true, 50),
    ('d43cb47a-683d-57f2-9629-1988772afe74', 'integrated_science', '통합과학', '통합', 'v1', null, null, true, 60),
    ('71d132fb-238f-5296-af51-869f69e57f4d', 'life_ethics', '생활과 윤리', '사회탐구', 'v1', null, null, true, 110),
    ('5597fd61-904e-5fd0-8426-a901f31e8009', 'ethics_thought', '윤리와 사상', '사회탐구', 'v1', null, null, true, 120),
    ('6f06297a-ede7-5a03-b130-e4da6fd08200', 'korean_geography', '한국지리', '사회탐구', 'v1', null, null, true, 130),
    ('d7665f30-741c-5a97-9530-99085fcfc85f', 'world_geography', '세계지리', '사회탐구', 'v1', null, null, true, 140),
    ('cf82e588-4309-5e5b-b593-4945f5541a3a', 'east_asian_history', '동아시아사', '사회탐구', 'v1', null, null, true, 150),
    ('5ceb7f37-8948-5917-9b79-db71b1d258a8', 'world_history', '세계사', '사회탐구', 'v1', null, null, true, 160),
    ('c6c44267-16f0-5657-b166-ec0a6b25b139', 'economics', '경제', '사회탐구', 'v1', null, null, true, 170),
    ('a22d614a-c6e8-5b83-af9a-ee4c85aeefa5', 'politics_law', '정치와 법', '사회탐구', 'v1', null, null, true, 180),
    ('57ec3296-d7a1-5eeb-bcd4-b7ae96c07112', 'society_culture', '사회·문화', '사회탐구', 'v1', null, null, true, 190),
    ('0764c70f-1f80-555b-ab8d-f81cddd36643', 'physics_1', '물리학Ⅰ', '과학탐구', 'v1', null, null, true, 210),
    ('2710d864-2933-55d0-8bb0-67b02a2d95b8', 'chemistry_1', '화학Ⅰ', '과학탐구', 'v1', null, null, true, 220),
    ('86e0339e-e610-56b1-8531-425e0b14418a', 'life_science_1', '생명과학Ⅰ', '과학탐구', 'v1', null, null, true, 230),
    ('315e6181-f764-5bf5-b392-2a5d65919568', 'earth_science_1', '지구과학Ⅰ', '과학탐구', 'v1', null, null, true, 240),
    ('31171ead-5998-5149-9a79-a62242cf2764', 'physics_2', '물리학Ⅱ', '과학탐구', 'v1', null, null, true, 250),
    ('19055543-21ed-5bc9-ba48-c5b05ad4695e', 'chemistry_2', '화학Ⅱ', '과학탐구', 'v1', null, null, true, 260),
    ('0f3aa8d1-226d-560c-9f9b-0e2dd99aa342', 'life_science_2', '생명과학Ⅱ', '과학탐구', 'v1', null, null, true, 270),
    ('1897530a-b75f-5785-b7de-dd3c41442a14', 'earth_science_2', '지구과학Ⅱ', '과학탐구', 'v1', null, null, true, 280)
on conflict (taxonomy_version, code) do nothing;

-- Expected: 23 rows inserted on a clean run, 0 on a rerun.
select count(*) as subjects_v1 from public.subjects where taxonomy_version = 'v1';

commit;
